///definir um método em uma classe abstrata que implemente a estrutura do algoritmo 
/// comum a todas as suas implementações específicas

public abstract class Relatorio {
    public abstract void gerarCabecalho();
    public abstract void gerarCorpo();
    public abstract void gerarSumario();
    public void gerar() { //template method
        gerarCabecalho();
        gerarCorpo();
        gerarSumario();
    }
}

public class RelatorioVendas extends Relatorio {
    public void gerarCabecalho() {
        //codigo pro cabeçalho
    }
    public void gerarCorpo() {
        //codigo pro corpo
    }
    public void gerarSumario(){
        //codigo pro sumario
    }
}